### ISSUE TITLE
returning a PlayerEntity.SleepFailureReason that has a null Text gives a NullPointerException in TRY_SLEEP event

### ISSUE THREAD

**Issue by MoriyaShiine** [TheIllusiveC4/Somnus#1]

**Comment by TheIllusiveC4** [comment]
I'm able to replicate this, but can you share your crash log so I can examine that as well?

**Comment by MoriyaShiine** [comment]
It doesn't crash and still works as expected aside from throwing the NPE, here's the log: https://pastebin.com/NWjecrUd

**Comment by MoriyaShiine** [comment]
It immediately expired, hold on

**Comment by MoriyaShiine** [comment]
https://hatebin.com/bmiuiwyfaq

**Comment by MoriyaShiine** [comment]
Ugh, pastebin is being stupid and removing my post the instant I reload the page, sorry for having to send the actual file.
[latest.log](https://github.com/TheIllusiveC4/Somnus/files/6053316/latest.log)

**Comment by TheIllusiveC4** [comment]
No worries, it's all good. Thanks for sharing that. I can confirm it's exactly the same issue I'm seeing in my tests.

At first glance, this seems like a vanilla bug since `BedBlock` never null-checks the text before sending the message. It just never gets encountered because vanilla never actually sends a null value. If that's the case, the fix seems pretty straightforward on my end.

However, it's very strange that Forge doesn't seem to have this issue despite the fact the code looks exactly the same and I'm trying to see if I can figure out why that is.
